theme = "catppuccin_mocha"
# theme = "nord-night"
# theme = "papercolor-dark"
# theme = "solarized_dark"

[editor]
line-number = "relative"
soft-wrap.enable = true
bufferline = "multiple"

[editor.indent-guides]
reder = true

[keys.normal]
"ret" = "goto_word"
"esc" = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
C-r = ":reload-all"
