# theme = "catppuccin_mocha"
theme = "nord-night"
# theme = "papercolor-dark"
# theme = "solarized_dark"

[editor]
line-number = "relative"
soft-wrap.enable = true

[keys.normal]
"ret" = "goto_word"

[keys.normal.space]
C-r = ":reload-all"
